### ISSUE TITLE
pillar.example needs vendor name

### ISSUE THREAD

**Issue by feinu** [saltstack-formulas/sbuild-formula#1]
The current pillar.example doesn't compile, as it's looking for a vendor name.

``` yaml
vendor:
  repositories:
    default: http://ftp.fr.debian.org/debian
```

should be

``` yaml
vendor:
  debian:
    repositories:
      default: http://ftp.fr.debian.org/debian
```
